---
title: "Women in Informal Employment in Latin America"
author: "Daniela Teran"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(ggplot2)
library(readr)
library(tidyr)
library(readxl)
library(janitor)

```

```{r,include=FALSE}

gii_latam <- read_excel(path = "GII.xlsx", skip = 1)%>%
  clean_names() %>%
  arrange(hdi_rank_2018) %>%
  filter(country %in% c("Argentina", "Bahamas", "Barbados", "Belize", "	Bolivia (Plurinational State of)", "Brazil", "Chile", "Colombia", "Costa Rica", "Cuba", "Dominican Republic", "Ecuador", "El Salvador", "Guatemala", "Guyana", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Saint Lucia", "Suriname", "Trinidad and Tobago", "Uruguay", "Venezuela"))
  
gii_latam

```
```{r, include=FALSE}

informal_latam <- read_excel(path = "Informal_employment.xlsx", skip = 3) %>%
  clean_names() %>%
  select(country_name, x2018) %>%
  filter(country_name %in% c("Argentina", "Bahamas", "Barbados", "Belize", "	Bolivia (Plurinational State of)", "Brazil", "Chile", "Colombia", "Costa Rica", "Cuba", "Dominican Republic", "Ecuador", "El Salvador", "Guatemala", "Guyana", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Saint Lucia", "Suriname", "Trinidad and Tobago", "Uruguay", "Venezuela"))

informal_latam
```

```{r, include=FALSE}

informal_latam_ilo <- read_excel(path = "Proportion_informal_employment.xlsx")%>%
  clean_names() %>%
  select(ref_area_label, sex_label, time, obs_value) %>%
  filter(ref_area_label %in% c("Argentina", "Bahamas", "Barbados", "Belize", "	Bolivia (Plurinational State of)", "Brazil", "Chile", "Colombia", "Costa Rica", "Cuba", "Dominican Republic", "Ecuador", "El Salvador", "Guatemala", "Guyana", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Saint Lucia", "Suriname", "Trinidad and Tobago", "Uruguay", "Venezuela")) %>%
  filter(sex_label %in% "Sex: Female")

informal_latam_ilo
```


```{r}

graph_informal_gii <- ggplot(informal_latam_ilo, aes(x = time, y = obs_value, color = ref_area_label)) +
  geom_line() + 
  geom_point(size = 0.5) +
  labs(title = "Women in Informal Employment in Latin America", 
       subtitle = "Harmonized Series",
       caption = "Data from the International Labour Organization (ILO)
                  Source: https://www.ilo.org/shinyapps/bulkexplorer38/
                          ?lang=en&segment=indicator&id=SDG_B831_SEX_RT_A",
       y = "Percentage (%)", 
       x = "Year",
       color = "Country")+
  scale_x_continuous(
    limits = c(2000, 2020),
    breaks = c(2000, 2005, 2010, 2015, 2020),
    label = c("2000", "'05", "'10", "'15", "2020")) +
  scale_y_continuous(
    limits = c(0, 100),
    breaks = c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100),
    labels = c("10", "20", "30", "40", "50", "60", "70", "80", "90", "100")) +
theme_minimal()

graph_informal_gii
  
```




