---
title: '2020-03-06'
author: "Daniela Teran"
date: "3/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **About**

## Gender inequality for Women in the Informal Economy in Latin America  

#### **Project Background and Motivations**  

Identity has several dimensions, including gender, race, sexuality, and class,
and these intersecting links influence a person’s daily life. Therefore, a
gender analysis that utilizes an intersectional lens is essential to designing
and implementing equitable international development projects. This project aims
to compare markers of gender inequality with data on women workers in the
informal economy in Latin A merica, with the goal of analyzing how this already
vulnerable group is restricted by issues of race, class, gender and culture.

#### **About the Data**

Gender Inequality Index - UNDP

"The GII sheds new light on the position of women in 162 countries; it yields insights in gender gaps in major areas of human development. The component indicators highlight areas in need of critical policy intervention and it stimulates proactive thinking and public policy to overcome systematic disadvantages of women".

Source:
http://hdr.undp.org/en/content/gender-inequality-index-gii

Informal Employment Index - World Bank

This data set cointains different information and markers around informal employment in the world. I have been cleaning the data to obtain only the information about Latin America and I am expecting to use the following markers: 

- Informal employment, female (% of total non-agricultural employment)

- Vulnerable employment, total (% of total employment) (modeled ILO estimate)

- Labor force participation rate, total (% of total population ages 15+) (national estimate)

- Unemployment, female (% of female labor force) (modeled ILO estimate)

Source:
https://data.worldbank.org/indicator/SL.ISV.IFRM.ZS

Proportion of informal employment - ILO: 

https://www.ilo.org/shinyapps/bulkexplorer38/?lang=en&segment=indicator&id=SDG_A831_SEX_RT_A

#### **About Me**

My name is Daniela Teran and I am a Masters in Design Engineering candidate, 2020. You can reach me at ``dteran@mde.harvard.edu``.

